version: "3"

services:
  progress-server:
    build:
      context: .
      dockerfile: ./docker/progress/Dockerfile
    container_name: "prgs_server"
    ports:
      - 25565:25565
    environment:
      SERVER_NAME: SHIKOSAI_XXXI_PROGRESS
      ICON: https://raw.githubusercontent.com/Colk-tech/shikosai-31-mc-server/main/assets/images/shikosai-31-mc-logo-x64.png
      MOTD: "§l§6第31回茨香祭§r §lマイクラバトル§r §l§n§a進捗部門§r へようこそ！"
      MAX_PLAYERS: 100
      DIFFICULTY: normal
      MODE: survival
      OPS: __def__,htrn_77,Colk_
      MEMORY: 116G
      TYPE: SPIGOT
      SPIGET_RESOURCES: 23799,70359,28140,1997
      # 遠隔操作用のパスワード。本番環境の際には必ず任意の値に変更すること。
      RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - progress-server-data:/data
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '7'
          memory: 120G

  progress-backup:
    image: itzg/mc-backup
    container_name: "prgs_backup"
    depends_on:
      - progress-server
    environment:
      BACKUP_NAME: prgs
      INITIAL_DELAY: 3m
      BACKUP_INTERVAL: 3m
      EXCLUDES: jar,cache
      # 遠隔操作用のパスワード。本番環境の際には必ず任意の値に変更すること。
      RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - progress-server-data:/data:ro
      - ./progress-server-backups:/backups
    network_mode: "service:progress-server"

volumes:
  progress-server-data:
    driver: local
